### ISSUE TITLE
Requires nonexistant module "Pre::Req"

### ISSUE THREAD

**Issue by qtplatypus** [ingydotnet/spiffy-pm#1]
There is a requirement for Pre::Req however this doesn't exist in cpan.

**Comment by kentfredric** [comment]
Its odd. Because its declared in Makefile.PL and META.json, but nowhere in code ...

**Comment by kentfredric** [comment]
Well, META.yml because you've regressed and failed to ship META.json

**Comment by ingydotnet** [comment]
Is it important to ship both META.{yaml,json} ?

**Comment by kentfredric** [comment]
It is very much recommended, META.json supports META 2.0 spec, META.yml does not.

Which means the nuances of different dependecy types is lost with .yml, amongst other things.  ( For instance, META.yml doesn't distinguish between `build` and `test` phases, so `test` depends are _alway_ required even if you're doing `--notest` )

Really, people should be using `.json` by _default_ in 2014, and `.yml` should be considered a legacy compatibility layer for tools that exist all over the place that haven't been adapted to the new system.

The biggest reason that its not already default in `[@Basic]` is that adding it now would result in a plugin+file collision for everyone who as added `[MetaJSON]` themselves some other way.

**Comment by ingydotnet** [comment]
That sounds like a dzil bug that could be fixed. Anyway, I changed my release process to add a META.json file, and I reshipped Spiffy-0.34. Closing this.
