### ISSUE TITLE
New warning in bleadperl might uncover a bug

### ISSUE THREAD

**Issue by andk** [ingydotnet/spiffy-pm#3]
When loading Test::Base with current bleadperl it warns four times:

Redundant argument in sprintf at /home/sand/src/perl/repoperls/installed-perls/perl/v5.21.1-40-g55149fe/127e/lib/site_perl/5.21.2/Spiffy.pm line 224.

https://metacpan.org/source/INGY/Spiffy-0.34/lib/Spiffy.pm#L224

The calling line in Test::Base for the first warning seems to be:

Spiffy::field("spec", "-init", "\$self->_spec_init") called at /home/sand/src/perl/repoperls/installed-perls/perl/v5.21.1-49-gc445c5b/9980/lib/site_perl/5.21.2/Test/Base.pm line 42

https://metacpan.org/source/INGY/Test-Base-0.62/lib/Test/Base.pm#L42

Let me know if you need more info

(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by andk** [comment]
I should have mentioned that some recent bleadperls produced FAIL reports. You can ignore those, the really, realy recent bleadperls above circa v5.21.1-65-gc97ab48 produce PASSes again.

**Comment by ingydotnet** [comment]
Fixed, released, thanks!!
